version: '3.1'
services:
  kurento:
    container_name: kurento-server 
    image: "kurento/kurento-media-server:latest"
    ports:
      - "0.0.0.0:8888:8888"
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes: 
      - ./turnserver/:/turnserver-4.5.1.1/docker/coturn/
    #  - ./coturn-kurento/:/etc/default/
      - ./tmp:/tmp
    environment:
      - "MEDIA_SERVER_HOST=kurento"
      - "MEDIA_SERVER_PORT=8888"
